
from turtle import *

def cir():
    width(4)
    color("black", "#96FED1")
    up()
    goto(0,-100)
    down()
    begin_fill()
    circle(150, 360)
    end_fill()
    
def head():

    #head
    width(4)
    color("black", "#FFDCB9")
    up()
    goto(0,0)
    down()
    begin_fill()
    circle(100, 270)
    end_fill()
    color("#FFDCB9", "#FFDCB9")
    begin_fill()
    circle(100, 90)
    end_fill()
    color("black", "#FFDCB9")
    up()
    goto(-70,-5)#100/SQRT(2)
    left(180)
    down()
    begin_fill()
    circle(-70, 165)
    end_fill()
    color("#FFDCB9", "#FFDCB9")
    begin_fill()
    circle(-70, 195)
    end_fill()

    color("black", "#FFDCB9")
    up()
    goto(-70,-5)
    down()
    begin_fill()
    goto(0,0)
    end_fill()

    #ear
    color("#FFDCB9", "#FFDCB9")
    up()
    goto(110,100)
    right(180)
    down()
    begin_fill()
    circle(-25, 360)
    end_fill()
    color("black", "#FFDCB9")
    up()
    goto(110,100)
    down()
    circle(-25, 235)
    up()
    goto(110,100)
    left(45)
    down()
    circle(25,45 )

    #eyes(黑眼珠)
    up()
    color("black", "black")
    goto(45,140)
    right(45)#<
    down()
    begin_fill()
    circle(30, 360)
    end_fill()
	#eyes(右白眼珠)
    up()
    color("white", "white")
    goto(45,120)
    down()
    begin_fill()
    circle(10 ,360)
    end_fill()
    #eyes(左黑眼珠)
    up()
    color("black", "black")
    goto(-45,140)
    down()
    begin_fill()
    circle(30, 360)
    end_fill()
    #eyes(左白眼珠)
    up()
    color("white", "white")
    goto(-45,120)
    down()
    begin_fill()
    circle(10 ,360)
    end_fill()
	
    #右邊細眉毛
    up()
    width(2)
    color("black")
    goto(45,160)
    down()
    circle(40, 90)
    up()
    left(90)#>
    goto(45,160)
    down()
    circle(-30, 70)
    #左邊細眉毛
    up()
    goto(-45,160)
    left(70)#>
    down()
    circle(-30, 90)
    up()
    right(90)#<
    goto(-45,160)
    down()
    circle(40, 70)
    right(70)#<

    #右邊粗眉毛
    up()
    width(18)
    color("black")
    goto(60,175)
    down()
    goto(10,165)
    #左邊粗眉毛
    up()
    color("black")
    goto(-70,180)
    down()
    goto(-20,165)

    #MOUSE
    up()
    left(10)
    width(4)
    color("black", "#930000")
    goto(-25,60)
    down()
    begin_fill()
    circle(25, 360)
    end_fill()

    #hair
    up()
    color("black", "black")
    goto(-50,186)
    right(150)
    down()
    begin_fill()
    circle(-100,120)
    goto(60,175)
    goto(-50,186)
    end_fill()

def body():
    width(4)
    up()
    color("black", "red")
    goto(-65,-5)
    right(90)
    down()
    begin_fill()
    forward(80)
    left(90)
    forward(135)
    left(90)
    forward(110)
    end_fill()
    right(90)#>
    #left hand
    up()
    goto(-63,-12)
    down()
    begin_fill()
    left(145)
    forward(48)
    left(90)
    forward(25)
    left(90)
    forward(66)
    end_fill()
    left(35)#>
    
    up()
    color("black", "#FFDCB9")
    goto(-117,25)
    down()
    right(180)
    begin_fill()
    circle(15,360)
    end_fill()
    right(180)#>
    
    #right hand
    up()
    color("black", "red")
    goto(65,-6)
    down()
    begin_fill()
    right(45)
    forward(48)
    right(90)
    forward(25)
    right(90)
    forward(65)
    end_fill()
    right(135)#>

    up()
    color("black", "#FFDCB9")
    goto(93,-34)
    right(180)#<
    down()
    begin_fill()
    circle(15,360)
    end_fill()
    right(180)#>

    
	
def main():
    reset()
    cir()
    body()
    head()
    ht()
    return "Done!"

if __name__ == '__main__':
    main()
    mainloop()
